/* Assemble the deployable Root Cause Unlocked site.
   Run from the workspace root:  node RCU-Site/assemble.mjs

   The site's own pages are hand-written and live in this folder. The things
   that are COPIED IN are the assessments and the retest companion: the
   canonical comprehensive assessment is the workspace root index.html (live,
   script-maintained), the canonical MSK pain assessment is the workspace
   root msk-assessment.html, and the canonical Root Tracker (daily check-ins,
   trends, assessment deltas, retake planner, provider report) is the
   workspace root rcu-tracker.html. They are deliberately NOT duplicated here
   by hand. This script copies them to RCU-Site/quiz/index.html,
   RCU-Site/msk/index.html, and RCU-Site/tracker/index.html so the deployed
   site serves them at /quiz, /msk, and /tracker.

   That keeps exactly one canonical copy of each assessment/tool. Never
   hand-edit the generated copies (2026-08-04: tracker/index.html had drifted
   from a hand-patch with no source of truth before this script picked it up;
   the drift was reconciled back into rcu-tracker.html, do not let it happen
   again): edit the root files and re-run this script. */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SITE = dirname(fileURLToPath(import.meta.url));
const WORKSPACE = join(SITE, '..');

const COPIES = [
  { src: 'index.html', dest: 'quiz' },
  { src: 'msk-assessment.html', dest: 'msk' },
  { src: 'rcu-tracker.html', dest: 'tracker' }
];

try {
  for (const c of COPIES) {
    const banner = `<!-- GENERATED by RCU-Site/assemble.mjs from the workspace root ${c.src}. Do not edit here. -->\n`;
    const html = await readFile(join(WORKSPACE, c.src), 'utf8');
    const destDir = join(SITE, c.dest);
    await mkdir(destDir, { recursive: true });
    await writeFile(join(destDir, 'index.html'), banner + html, 'utf8');
    const kb = Math.round(Buffer.byteLength(html) / 1024);
    console.log(`assembled: ${c.dest}/index.html (${kb} KB) from root ${c.src}`);
  }
  console.log('site is ready to deploy. Upload the contents of RCU-Site/ to the host.');
} catch (err) {
  console.error('assemble failed:', err.message);
  process.exitCode = 1;
}
