/* Assemble the deployable Root Cause Unlocked site.
   Run from the workspace root:  node RCU-Site/assemble.mjs

   The site's own pages are hand-written and live in this folder. The things
   that are COPIED IN are the assessments and the retest companion: the
   canonical comprehensive assessment is the workspace root index.html (live,
   script-maintained), the canonical MSK pain assessment is the workspace
   root msk-assessment.html, the canonical Root Tracker (daily check-ins,
   trends, assessment deltas, retake planner, provider report) is the
   workspace root rcu-tracker.html, and the canonical thyroid deep-dive
   screener is the workspace root rcu-thyroid.html. They are deliberately NOT
   duplicated here by hand. This script copies them to RCU-Site/quiz/,
   RCU-Site/msk/, RCU-Site/tracker/ and RCU-Site/thyroid/ so the deployed site
   serves them at /quiz, /msk, /tracker, and /thyroid.

   That keeps exactly one canonical copy of each assessment/tool. Never
   hand-edit the generated copies (2026-08-04: tracker/index.html had drifted
   from a hand-patch with no source of truth before this script picked it up;
   the drift was reconciled back into rcu-tracker.html, do not let it happen
   again): edit the root files and re-run this script. */

import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SITE = dirname(fileURLToPath(import.meta.url));
const WORKSPACE = join(SITE, '..');

const COPIES = [
  { src: 'index.html', dest: 'quiz' },
  { src: 'msk-assessment.html', dest: 'msk' },
  { src: 'rcu-tracker.html', dest: 'tracker' },
  { src: 'rcu-thyroid.html', dest: 'thyroid' }
];

/* SAFETY GUARD, added 2026-08-26.
   The "one canonical copy" rule above has been broken in practice, exactly the
   way the 2026-08-04 note warned about. On 2026-08-26 a plain run of this
   script would have silently reverted three pieces of live work, because the
   deployed pages are NEWER than the roots that generate them:
     - the /quiz early-exit feature (added 2026-08-24, the fix for 45 views
       producing 1 completion)
     - the ranked-list tripwire fix (2026-08-22)
     - the Root Health to Root Cause Unlocked rebrand on /quiz and /msk
   So: never overwrite a destination that is newer than its source. Skip it,
   say so, and exit non-zero so a caller notices. Pass --force only after the
   source has genuinely been reconciled. */
const FORCE = process.argv.includes('--force');
let skipped = 0;

try {
  for (const c of COPIES) {
    const srcPath = join(WORKSPACE, c.src);
    const destPath = join(SITE, c.dest, 'index.html');

    const banner = `<!-- GENERATED by RCU-Site/assemble.mjs from the workspace root ${c.src}. Do not edit here. -->\n`;
    const html = await readFile(srcPath, 'utf8');

    if (!FORCE) {
      const [srcStat, destStat] = await Promise.all([
        stat(srcPath).catch(() => null),
        stat(destPath).catch(() => null)
      ]);
      if (srcStat && destStat && destStat.mtimeMs > srcStat.mtimeMs) {
        // Newer mtime alone is not drift: a rebuild, a checkout or a copy all
        // bump it while leaving the bytes identical. Only refuse when the
        // deployed page actually differs from what the source would produce.
        // Line endings are normalized first, because git's autocrlf rewrites
        // them on checkout and would otherwise flag every page as drifted.
        const current = await readFile(destPath, 'utf8').catch(() => null);
        const normalize = (s) => (s === null ? null : s.replace(/\r\n/g, '\n'));
        if (normalize(current) !== normalize(banner + html)) {
          console.warn(
            `SKIPPED: ${c.dest}/index.html is newer than root ${c.src} AND its content ` +
            `differs. The deployed page has edits the source does not. Reconcile them ` +
            `into the root file, or rerun with --force to discard the deployed version.`
          );
          skipped++;
          continue;
        }
      }
    }

    await mkdir(join(SITE, c.dest), { recursive: true });
    await writeFile(destPath, banner + html, 'utf8');
    const kb = Math.round(Buffer.byteLength(html) / 1024);
    console.log(`assembled: ${c.dest}/index.html (${kb} KB) from root ${c.src}`);
  }

  if (skipped) {
    console.error(
      `\n${skipped} page(s) skipped to avoid reverting live work. Nothing was overwritten.`
    );
    process.exitCode = 1;
  } else {
    console.log('site is ready to deploy. Upload the contents of RCU-Site/ to the host.');
  }
} catch (err) {
  console.error('assemble failed:', err.message);
  process.exitCode = 1;
}
